apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deployment
  namespace: project3
spec:
  replicas: 3
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: backend
        image: alexandrebo/final-project-backend:1.0
        resources:
          requests:
            memory: "500Mi"
            cpu: "500m"
          limits:
            memory: "1Gi"
            cpu: "1"
        ports:
        - containerPort: 8706
        envFrom:
        - configMapRef:
            name: backend-config
        - secretRef:
            name: backend-secrets