apiVersion: v1
kind: ConfigMap
metadata:
  name: backend-config
  namespace: project3
data:
  PORT: "8706"
  DATABASE_URI: "mongodb://root:example@mongo-service.project3.svc.cluster.local:27017"
  REDIS_HOST: "redis-service.project3.svc.cluster.local"
  REDIS_PORT: "6379"